### ISSUE TITLE
Cannot find Zephyr v2.6 branch 

### ISSUE THREAD

**Issue by cpavot** [platformio/zephyr#10]
Dear @valeros,

I already asked the question in https://github.com/platformio/zephyr/issues/8 but since this one is Closed, I guess it is preferable to raise a new one.

Can you please clarify where I can find Zephyr v2.6 branch in platformio zephyr project?

I need to port some patches on top of it for my own purposes and I'm confused now about how to proceed as the last commit seems to be from March 9th 2021 on branch v2.5.

Thanks a lot.

**Comment by valeros** [comment]
Resolved in https://github.com/platformio/zephyr/commit/b3c14b2bd9a41cc6bd9342879c0da360f8dc929d
