### ISSUE TITLE
get_zephyr_venv_dir() doesn't work for Git-linked Zephyr

### ISSUE THREAD

**Issue by maxgerhardt** [platformio/zephyr#25]
When e.g. using the fork https://github.com/CommunityGD32Cores/zephyr/tree/v4.0-branch-package and referencing in a platform via the `platform.json` via

```json
    "framework-zephyr": {
      "type": "framework",
      "optional": true,
      "owner": "platformio",
      "version": "https://github.com/CommunityGD32Cores/zephyr.git#v4.0-branch-package"
    },
```
then, the function 

https://github.com/platformio/zephyr/blob/c2a98a8b4b316e5e28132788d1cbaeb52a94fb12/scripts/platformio/platformio-build.py#L1514-L1523

will always fail with 
```
TypeError: can only concatenate str (not "NoneType") to str:
..
  File "C:\Users\Max\.platformio\packages\framework-zephyr\scripts\platformio\platformio-build.py", line 1646:
    venv_dir = get_zephyr_venv_dir()
  File "C:\Users\Max\.platformio\packages\framework-zephyr\scripts\platformio\platformio-build.py", line 1525:
    env.subst("$PROJECT_CORE_DIR"), "penv", ".zephyr-" + zephyr_version
========================== [FAILED] Took 2.60 seconds ==========================
```

Explicitly printing out the package version and the output from `version.get_original_version()` shows
```
Package version: 2.40000.0+sha.06c64d4f
Zephyr version: None
```
So, it can't handle the `+sha.06c64d4f` part.

This prevents using one's own Zephyr package in a platform (without fixing up this error somehow), when e.g. adding a new HAL is needed.

**Comment by maxgerhardt** [comment]
Quick-Fix: Fall back to the package version and cleanup some special characters: https://github.com/CommunityGD32Cores/zephyr/commit/511e5f333d47d44f8ec5813885ac301574c67909

This way forks will have their own penv folder and don't e.g. share it with the mainline Zephyr 4.0.0 penv folder.

**Comment by valeros** [comment]
Thanks for reporting, fixed!
