### ISSUE TITLE
scripts/platformio/platformio-build.py:

### ISSUE THREAD

**Issue by hvegh** [platformio/zephyr#7]
https://github.com/platformio/zephyr/blob/75bc7697b289f18fe71e0b16197676272558e6c8/scripts/platformio/platformio-build.py#L79

Dear platformio devs,

Can we add **rv32im** to the supported architectures?
 
`elif board_config.get("build.march", "") in ("rv64imac", "rv32imac", **"rv32im"**):
`
I am trying to support litex_vexriscv  , judging from the litex compiler options  the AC extensions are not supported for the vexriscv core. 

See [https://github.com/hvegh/platform-litex](https://github.com/hvegh/platform-litex) for preliminary litex-riscv support with zephyr....

**Comment by valeros** [comment]
Resolved in https://github.com/platformio/zephyr/commit/b3c14b2bd9a41cc6bd9342879c0da360f8dc929d

**Comment by hvegh** [comment]
great tnx
